### ISSUE TITLE
AGPL License requires source code to be published

### ISSUE THREAD

**Issue by mslinn** [opszero/buy-button#3]
See https://en.wikipedia.org/wiki/Affero_General_Public_License
"the full source code be made available to any network user of the AGPL-licensed work, typically a web application".

Because GPL "infects" any code that it is combined with, any modifications to the code will require those changes to be available. Complying with that requirement in a secure manner is onerous, and prevents me from considering the usage of this code.

Is a commercial license available for this code? The Buy Now button (https://plasso.com/s/kcBMcO3FE1) gives a 404 error.

**Comment by abhiyerra** [comment]
Hey @mslinn yeah. I can license the code commercially. Does $99 dollars seem fair?
